### ISSUE TITLE
翻译不完整

### ISSUE THREAD

**Issue by sunnyelf** [ewen0930/PhpStorm-Chinese#11]
为什么有些地方还是英文？比如打开菜单栏的文件选项，下面还有类似Open URL...，Save As..等等

**Comment by ewen0930** [comment]
是的

**Comment by sunnyelf** [comment]
我也研究很久，就是没有找到原因所在。

**Comment by ewen0930** [comment]
https://github.com/ewen0930/PyCharm-Chinese/issues/3
