### ISSUE TITLE
找不到resources_zh_CN.jar

### ISSUE THREAD

**Issue by hackerking0830** [ewen0930/PhpStorm-Chinese#12]
請問一下 這個檔案在哪邊? 翻了好久都找不到
我run package.cmd 也是同樣

**Comment by iDvel** [comment]
运行`$ ./package.cmd`
得到`resources_zh.jar`

**Comment by ewen0930** [comment]
或者下载releases里面百度云的打包好的文件！
最近github传附件总是失败……

**Comment by hackerking0830** [comment]
releases在哪邊呢?

**Comment by ewen0930** [comment]
！！！
Code列表，上面有4个按钮（ 18 commits    --   1 branch  --  12 releases   --  1 contributor）
第三个 （releases）

**Comment by ewen0930** [comment]
releases 里包文件在  mac 上是可用的，麻烦看一下上面回复

**Comment by zhangxxyz** [comment]
> @zhangxxyz 【发布】里包文件在mac上是可用的，麻烦看一下上面回复

enen，当时就找到了的，不过当时忘了回复，谢谢你
