### ISSUE TITLE
“文件”菜单内，“开放目录”应为“打开目录”

### ISSUE THREAD

**Issue by LinXiaoya** [ewen0930/PhpStorm-Chinese#15]
![image](https://user-images.githubusercontent.com/9798537/32597508-e4784326-c571-11e7-9565-52621008889a.png)

**Comment by ewen0930** [comment]
谢谢指正，已修复；应该是某次同步出错了

**Comment by ewen0930** [comment]
这个“打开目录...”应该是多余的功能，和“打开...”功能一样，在PyCharm和WebStorm里没发现有这个子菜单！
