### ISSUE TITLE
Mac 版的 PhpStorm 2017.2 无法使用

### ISSUE THREAD

**Issue by zhcexo** [ewen0930/PhpStorm-Chinese#16]
把语言包放到 phpstorm.app/contents/lib 里面，并不会出现中文界面
是我放错了位置，还是说跟新版本的不兼容？

**Comment by imnpc** [comment]
测试无误 可以放进去

**Comment by zhcexo** [comment]
需要在 Mac 下重新打包生成 jar 文件吗？还是说直接用 windows 下生成的？

**Comment by imnpc** [comment]
https://github.com/ewen0930/PhpStorm-Chinese/releases/download/0.6.2-beta-v2017.2/PhpStorm_2017.2_zh_utf-8.zip
直接下载的最新版本的汉化包  解压以后将文件复制过去  重启软件就好用了

**Comment by zhcexo** [comment]
谢谢，解决！
