### ISSUE TITLE
拷贝进去，全部是乱码了

### ISSUE THREAD

**Issue by herozzm** [ewen0930/PhpStorm-Chinese#2]
是不是翻译文件编码有问题，64 w7

**Comment by imnpc** [comment]
WIN 10下面是正常的  不过最新版是2016.1了

**Comment by ewen0930** [comment]
@herozzm 没遇到过乱码问题，不知道你是怎么弄的； 
@imnpc 2016.1更新了

**Comment by fax001** [comment]
应该是某些系统字体的问题
修改编辑器默认字体可以解决
大概就是这个样子的
![snipaste20170518_105605](https://cloud.githubusercontent.com/assets/1317574/26184805/922c9726-3bb9-11e7-9ad2-e43f3a5e1ee5.png)
![snipaste20170518_105934](https://cloud.githubusercontent.com/assets/1317574/26184809/9682bfee-3bb9-11e7-9037-a9aa284b6e77.png)
![snipaste20170518_105952](https://cloud.githubusercontent.com/assets/1317574/26184811/9865bc30-3bb9-11e7-8341-83ca34a32bc6.png)

**Comment by ewen0930** [comment]
后面的更新，统一转码过，应该没问题了吧
