### ISSUE TITLE
感謝開發，PhpStorm for MAC使用正常

### ISSUE THREAD

**Issue by kamicreator** [ewen0930/PhpStorm-Chinese#3]
OS：OS X EI Capitan(10.11.3)
PhpStorm 10.0.3

使用上一切正常

**Comment by sogog** [comment]
macOS：10.12.1
PHPstorm 2016.3
PhpStorm_2016.2_zh.zip
使用一切正常。感谢作者！

**Comment by ewen0930** [comment]
@sogog PhpStorm2016.3也更新汉化包了，欢迎测试

**Comment by luyi61** [comment]
macOS：10.12.3
PHPstorm 2017.1
PhpStorm_2017.1_zh_utf-8.zip

无法使用

**Comment by ewen0930** [comment]
@luyi61 是有乱码还是没效果？

**Comment by luyi61** [comment]
我昨天升级到了macOS10.12.4之后，重新复制了下是可以的。
10.12.3的时候是无效不是乱码，不过我系统升级了，没法重现了。
