### ISSUE TITLE
phpstorm2016.3.1不生效

### ISSUE THREAD

**Issue by xutunan** [ewen0930/PhpStorm-Chinese#8]
我用的是phpstorm2016.3.1，为什么把压缩包里的"resources_zh_CN.jar"拷贝到PhpStorm安装目录下的lib目录，重启之后，还是不生效？望解答，谢谢。

**Comment by ewen0930** [comment]
你是用的phpStorm2016.3的语言包版本吗？
https://github.com/ewen0930/PhpStorm-Chinese/releases/tag/0.5.9-beta-v2016.3
Github或百度云下载 PhpStorm_2016.3_zh.zip，用这个压缩包里的！

我用的就是phpStorm2016.3.1，没有问题！
